name: Python Linting and Tests

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on PRs to the main branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']  # Specify the versions of Python to test against

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort pytest  # Add other dependencies as needed
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Flake8 (linting)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # Customize rules as needed
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Black (auto-format)
        run: |
          black .
        continue-on-error: true

      - name: Run Isort (auto-sort imports)
        run: |
          isort .
        continue-on-error: true

      - name: Run Pytest (unit tests)
        run: |
          pytest
